name: CI on Linux
on: [push]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
        cache-dependency-path: vscode/yarn.lock
    - run: |
        yarn
        yarn core-ci
        yarn extensions-ci
        yarn gulp vscode-reh-web-darwin-arm64-min-ci
      working-directory: ./vscode
