name: CI on Linux
env:
  cache-version: v11
on: [push]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: yarn
      working-directory: ./vscode
